if ((vehicle player isKindof "I_Heli_light_03_unarmed_F") or (vehicle player isKindof "B_Heli_Light_01_F")) then
{
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellRed" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShell" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
Smoke = "SmokeShellBlue" createVehicle [getPos (vehicle player) select 0, getPos (vehicle player) select 1,0];
sleep 0.2;
}